service: neytrack

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    AWS_REGION: us-east-1
    WORKSPACE: sdx
    DYNAMODB_TABLE: ${self:service}-games-${opt:stage, 'sdx'}

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    sourcemap: true
    watch:
      pattern: ["src/**/*"]

functions:
  neytrack-list:
    handler: src/controllers/list/index.handler
    event:
      - http:
        path: games/titular
        method: get

resources:
  Resources:
    GamesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-games-${opt:stage, 'sdx'}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
