service: neytrack

provider:
  name: aws
  stage: sdx
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-games-${opt:stage, 'sdx'}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true

functions:
  neytrack-list-games:
    handler: src/controllers/list/index.handler
    events:
      - http:
          path: games
          method: get

  neytrack-get-game:
    handler: src/controllers/get/index.handler
    events:
      - http:
          path: games/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

  neytrack-delete-game:
    handler: src/controllers/delete/index.handler
    events:
      - http:
          path: games/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true

  neytrack-create-game:
    handler: src/controllers/create/index.handler
    events:
      - http:
          path: games
          method: post

  neytrack-update-game:
    handler: src/controllers/update/index.handler
    events:
      - http:
          path: games/{id}
          method: put
          request:
            parameters:
              paths:
                id: true

resources:
  Resources:
    GamesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-games-${opt:stage, 'sdx'}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-api
        Description: API for ${self:service}
